### ISSUE TITLE
Crash: Hitting dragon with burning Arrow `EntityDragonPart cannot be cast to EntityLivingBase`

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#115]
Steps to reproduce:

1. Take a bow
2. Enchant with "Flame" enchantment (shooting burning arrows)
3. Hit a IceAndFire dragon (and probably vanilla dragon too)
4. Game crashes

```less
Caused by: java.lang.ClassCastException: com.github.alexthe666.iceandfire.entity.EntityDragonPart cannot be cast to net.minecraft.entity.EntityLivingBase
	at net.minecraft.entity.projectile.EntityArrow.redirect$zeb000$utBlockFire(EntityArrow.java:731) ~[aeh.class:?]
	at net.minecraft.entity.projectile.EntityArrow.onHit(EntityArrow.java:366) ~[aeh.class:?]
```

Set this option to `false` fixing this crash:

```zs
# Prevents fire projectiles burning entities when blocking with shields
B:"Block Fire"=false
```

[debug.zip](https://github.com/ACGaming/UniversalTweaks/files/11088234/debug.zip)

**Comment by ACGaming** [comment]
This is how you file an issue report! 👏
