### ISSUE TITLE
Crash: Ticking entity NullPointerException utMediumBoltFocusSound

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#184]
After updating to `UniversalTweaks-1.12.2-1.6.0`, killing `Eldritch Turret` from mod `Thaumic Augmentation` causing crash:

```less
NullPointerException
	at thaumcraft.common.items.casters.foci.FocusMediumBolt.handler$bab000$utMediumBoltFocusSound(FocusMediumBolt.java:525) ~[FocusMediumBolt.class:?]
	at thaumcraft.common.items.casters.foci.FocusMediumBolt.execute(FocusMediumBolt.java:78) ~[FocusMediumBolt.class:?]
	at thecodex6824.thaumicaugmentation.common.item.foci.FocusMediumBoltCompat.execute(FocusMediumBoltCompat.java:59) ~[FocusMediumBoltCompat.class:?]
	at thaumcraft.api.casters.FocusEngine.runFocusPackage(FocusEngine.java:122) ~[FocusEngine.class:?]
	at thaumcraft.api.casters.FocusEngine.castFocusPackage(FocusEngine.java:70) ~[FocusEngine.class:?]
	at thecodex6824.thaumicaugmentation.common.entity.EntityAutocasterBase.attackEntityWithFocus(EntityAutocasterBase.java:194) ~[EntityAutocasterBase.class:?]
	at thecodex6824.thaumicaugmentation.common.entity.EntityAutocasterBase.TickCentral_TrueOnUpdateTick(EntityAutocasterBase.java:152) ~[EntityAutocasterBase.class:?]
```

[latest.log](https://github.com/ACGaming/UniversalTweaks/files/11471342/latest.14.log)
[UniversalTweaks.cfg](https://github.com/ACGaming/UniversalTweaks/files/11471343/UniversalTweaks.txt)

**Comment by ACGaming** [comment]
Thanks for reporting, fixed for the upcoming release. For now, you can just disable the foci sound tweaks via config.
