### ISSUE TITLE
Stronghold tweak log error

### ISSUE THREAD

**Issue by xJon** [ACGaming/UniversalTweaks#185]
```
  [Server thread/WARN]: Failed Start with id Stronghold
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: java.lang.InstantiationException: mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.MapGenSafeStronghold$Start
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at java.lang.Class.newInstance(Class.java:427)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.gen.structure.MapGenStructureIO.func_143035_a(SourceFile:73)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.gen.structure.MapGenStructure.func_143027_a(MapGenStructure.java:201)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.MapGenSafeStronghold.generateSafeStructure(MapGenSafeStronghold.java:37)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.SafeStrongholdWorldGenerator.generate(SafeStrongholdWorldGenerator.java:24)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1020)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:980)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.management.PlayerChunkMapEntry.func_187268_a(PlayerChunkMapEntry.java:126)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.management.PlayerChunkMap.func_72693_b(SourceFile:147)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.world.WorldServer.func_72835_b(WorldServer.java:227)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:756)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:185)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
  [Server thread/INFO]: [net.minecraft.world.gen.structure.MapGenStructureIO:func_143035_a:77]: 	at java.lang.Thread.run(Thread.java:750)
  [Server thread/INFO]: [java.lang.Throwable:printStackTrace:635]: Caused by: java.lang.NoSuchMethodException: mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.MapGenSafeStronghold$Start.<init>()
  [Server thread/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.Class.getConstructor0(Class.java:3082)
  [Server thread/INFO]: [java.lang.Throwable:printStackTrace:635]: 	at java.lang.Class.newInstance(Class.java:412)
  [Server thread/INFO]: [java.lang.Throwable:printStackTrace:635]: 	... 16 more
  [Server thread/WARN]: Skipping Structure with id Stronghold
```
I'm not sure what caused this, I just noticed it in the game log.

**Comment by ACGaming** [comment]
Is this easily reproducable?

**Comment by xJon** [comment]
@ACGaming Seems to happen often enough upon Stronghold generation (you can use `/locate Stronghold`).

**Comment by ACGaming** [comment]
Seems to be modpack-specific, further handling in #207.
