### ISSUE TITLE
Crash with the stronghold fix

### ISSUE THREAD

**Issue by nocturni** [ACGaming/UniversalTweaks#207]
Howdy, this is a crash I got on a vanilla forge server using the stronghold fix. I think that for now I will disable it and use "Save My Stronghold!" instead. 

https://pastebin.com/4Y4P8HKt

**Comment by ACGaming** [comment]
There‘s some mod incompatibility involved, similar to #185. Haven‘t found the cause yet!

**Comment by nocturni** [comment]
Hm.. only mods I have that alter anything related to caves is Better Caves, Quark and Charm

**Comment by ACGaming** [comment]
Better Caves doesn‘t touch strongholds at all, Quark only adds to the stronghold loot tables. Can only imagine Charm since it directly accesses stronghold structures but couldn‘t reproduce the issue with only Universal Tweaks and Charm involved.

**Comment by ACGaming** [comment]
Can you provide the `debug.log` file containing the crash?

**Comment by Dan4oby** [comment]
> Hm.. only mods I have that alter anything related to caves is Better Caves, Quark and Charm

I have Worleys Caves, Quark, Charm and had same crash

**Comment by nocturni** [comment]
Sorry for the late answer, seems like I lost the debug.log I had before, although I think just installing quark and charm will make it crash

**Comment by ACGaming** [comment]
Tested the following scenarios:
* Charm 1.4.1 + Quark 1.6-179
* Charm 1.4.1 + Quark 1.6-179 + YUNG‘s Better Caves 2.0.4
* Charm 1.4.1 + Quark 1.6-179 + Worley‘s Caves 1.5.2
Tested with default configs and 3+ worlds each, can‘t reproduce any crash. There have to be other mods or at least config changes involved.

**Comment by josiah-roberts** [comment]
Same crash on [GregTech Community Pack](https://www.curseforge.com/minecraft/modpacks/gregtech-community-pack), version 1.7.1.

```
net.minecraft.util.ReportedException: Exception ticking world
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:397) ~[nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
        at java.lang.Thread.run(Thread.java:748) [?:1.8.0_212]
Caused by: java.lang.ClassCastException: net.minecraft.world.gen.structure.MapGenStronghold$Start cannot be cast to mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.MapGenSafeStronghold$Start
        at mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.MapGenSafeStronghold.generateSafeStructure(MapGenSafeStronghold.java:43) ~[MapGenSafeStronghold.class:?]
        at mod.acgaming.universaltweaks.tweaks.world.stronghold.worldgen.SafeStrongholdWorldGenerator.generate(SafeStrongholdWorldGenerator.java:24) ~[SafeStrongholdWorldGenerator.class:?]
        at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167) ~[GameRegistry.class:?]
        at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020) ~[axw.class:?]
        at net.minecraft.world.chunk.Chunk.populate(Chunk.java:990) ~[axw.class:?]
        at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157) ~[on.class:?]
        at net.minecraft.server.management.PlayerChunkMapEntry.providePlayerChunk(PlayerChunkMapEntry.java:126) ~[ot.class:?]
        at net.minecraft.server.management.PlayerChunkMap.tick(SourceFile:147) ~[ou.class:?]
        at net.minecraft.world.WorldServer.tick(WorldServer.java:227) ~[oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
        ... 4 more
```

After reloading the server twice, the stronghold managed to generate.
