### ISSUE TITLE
Abnormal exit of the game 

### ISSUE THREAD

**Issue by MokoBlack** [ACGaming/UniversalTweaks#283]
Command: "C:\\Program Files\\Java\\jre1.8.0_361\\bin\\java.exe" -Dminecraft.client.jar=.minecraft\versions\1.12.2\1.12.2.jar -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=16M -XX:-UseAdaptiveSizePolicy -XX:-OmitStackTraceInFastThrow -Xmn128m -Xmx3020m -Dfml.ignoreInvalidMinecraftCertificates=true -Dfml.ignorePatchDiscrepancies=true -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Djava.library.path=D:\特别整合包\TFC\.minecraft\versions\1.12.2-forge1.12.2-14.23.5.2847\1.12.2-forge1.12.2-14.23.5.2847-natives -Dminecraft.launcher.brand=HMCL -Dminecraft.launcher.version=3.2.134 -cp D:\特别整合包\TFC\.minecraft\libraries\net\minecraftforge\forge\1.12.2-14.23.5.2847\forge-1.12.2-14.23.5.2847.jar;D:\特别整合包\TFC\.minecraft\libraries\net\minecraft\launchwrapper\1.12\launchwrapper-1.12.jar;D:\特别整合包\TFC\.minecraft\libraries\org\ow2\asm\asm-all\5.2\asm-all-5.2.jar;D:\特别整合包\TFC\.minecraft\libraries\org\jline\jline\3.5.1\jline-3.5.1.jar;D:\特别整合包\TFC\.minecraft\libraries\net\java\dev\jna\jna\4.4.0\jna-4.4.0.jar;D:\特别整合包\TFC\.minecraft\libraries\com\typesafe\akka\akka-actor_2.11\2.3.3\akka-actor_2.11-2.3.3.jar;D:\特别整合包\TFC\.minecraft\libraries\com\typesafe\config\1.2.1\config-1.2.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-actors-migration_2.11\1.1.0\scala-actors-migration_2.11-1.1.0.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-compiler\2.11.1\scala-compiler-2.11.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-library_2.11\1.0.2\scala-continuations-library_2.11-1.0.2.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\plugins\scala-continuations-plugin_2.11.1\1.0.2\scala-continuations-plugin_2.11.1-1.0.2.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-library\2.11.1\scala-library-2.11.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-parser-combinators_2.11\1.0.1\scala-parser-combinators_2.11-1.0.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-reflect\2.11.1\scala-reflect-2.11.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-swing_2.11\1.0.1\scala-swing_2.11-1.0.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\scala-lang\scala-xml_2.11\1.0.2\scala-xml_2.11-1.0.2.jar;D:\特别整合包\TFC\.minecraft\libraries\lzma\lzma\0.0.1\lzma-0.0.1.jar;D:\特别整合包\TFC\.minecraft\libraries\net\sf\jopt-simple\jopt-simple\5.0.3\jopt-simple-5.0.3.jar;D:\特别整合包\TFC\.minecraft\libraries\java3d\vecmath\1.5.2\vecmath-1.5.2.jar;D:\特别整合包\TFC\.minecraft\libraries\net\sf\trove4j\trove4j\3.0.3\trove4j-3.0.3.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\maven\maven-artifact\3.5.3\maven-artifact-3.5.3.jar;D:\特别整合包\TFC\.minecraft\libraries\com\mojang\patchy\1.1\patchy-1.1.jar;D:\特别整合包\TFC\.minecraft\libraries\oshi-project\oshi-core\1.1\oshi-core-1.1.jar;D:\特别整合包\TFC\.minecraft\libraries\net\java\dev\jna\platform\3.4.0\platform-3.4.0.jar;D:\特别整合包\TFC\.minecraft\libraries\com\ibm\icu\icu4j-core-mojang\51.2\icu4j-core-mojang-51.2.jar;D:\特别整合包\TFC\.minecraft\libraries\com\paulscode\codecjorbis\20101023\codecjorbis-20101023.jar;D:\特别整合包\TFC\.minecraft\libraries\com\paulscode\codecwav\20101023\codecwav-20101023.jar;D:\特别整合包\TFC\.minecraft\libraries\com\paulscode\libraryjavasound\20101123\libraryjavasound-20101123.jar;D:\特别整合包\TFC\.minecraft\libraries\com\paulscode\librarylwjglopenal\20100824\librarylwjglopenal-20100824.jar;D:\特别整合包\TFC\.minecraft\libraries\com\paulscode\soundsystem\20120107\soundsystem-20120107.jar;D:\特别整合包\TFC\.minecraft\libraries\io\netty\netty-all\4.1.9.Final\netty-all-4.1.9.Final.jar;D:\特别整合包\TFC\.minecraft\libraries\com\google\guava\guava\21.0\guava-21.0.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\commons\commons-lang3\3.5\commons-lang3-3.5.jar;D:\特别整合包\TFC\.minecraft\libraries\commons-io\commons-io\2.5\commons-io-2.5.jar;D:\特别整合包\TFC\.minecraft\libraries\commons-codec\commons-codec\1.10\commons-codec-1.10.jar;D:\特别整合包\TFC\.minecraft\libraries\net\java\jinput\jinput\2.0.5\jinput-2.0.5.jar;D:\特别整合包\TFC\.minecraft\libraries\net\java\jutils\jutils\1.0.0\jutils-1.0.0.jar;D:\特别整合包\TFC\.minecraft\libraries\com\google\code\gson\gson\2.8.0\gson-2.8.0.jar;D:\特别整合包\TFC\.minecraft\libraries\com\mojang\authlib\1.5.25\authlib-1.5.25.jar;D:\特别整合包\TFC\.minecraft\libraries\com\mojang\realms\1.10.22\realms-1.10.22.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\commons\commons-compress\1.8.1\commons-compress-1.8.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\httpcomponents\httpclient\4.3.3\httpclient-4.3.3.jar;D:\特别整合包\TFC\.minecraft\libraries\commons-logging\commons-logging\1.1.3\commons-logging-1.1.3.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\httpcomponents\httpcore\4.3.2\httpcore-4.3.2.jar;D:\特别整合包\TFC\.minecraft\libraries\it\unimi\dsi\fastutil\7.1.0\fastutil-7.1.0.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\logging\log4j\log4j-api\2.8.1\log4j-api-2.8.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\apache\logging\log4j\log4j-core\2.8.1\log4j-core-2.8.1.jar;D:\特别整合包\TFC\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl\2.9.4-nightly-20150209\lwjgl-2.9.4-nightly-20150209.jar;D:\特别整合包\TFC\.minecraft\libraries\org\lwjgl\lwjgl\lwjgl_util\2.9.4-nightly-20150209\lwjgl_util-2.9.4-nightly-20150209.jar;D:\特别整合包\TFC\.minecraft\libraries\com\mojang\text2speech\1.10.3\text2speech-1.10.3.jar;D:\特别整合包\TFC\.minecraft\versions\1.12.2\1.12.2.jar net.minecraft.launchwrapper.Launch --username Moko_Black --version "HMCL 3.2.134" --gameDir D:\特别整合包\TFC\.minecraft --assetsDir D:\特别整合包\TFC\.minecraft\assets --assetIndex 1.12 --uuid 6df43c1944b74801813462e235be6421 --accessToken eyJhbGciOiJIUzI1NiJ9.eyJhZ2ciOiJBZHVsdCIsInN1YiI6IjIwNWU5NTNjMjg0MDQzMjZiNGU2NDdkMTdmMGVmZmMzIiwibGltIjoibXNhZm9yY2VkIiwieWdndCI6ImU2ZDk2NzExMGM1NzQ1YzliYzA1MWY2NjVmM2MwNzZlIiwic3ByIjoiNmRmNDNjMTk0NGI3NDgwMTgxMzQ2MmUyMzViZTY0MjEiLCJpc3MiOiJZZ2dkcmFzaWwtQXV0aCIsImZsYWdzIjpbIm1zYWZvcmNlZCIsIm1pbmVjcmFmdF9uZXQiXSwiZXhwIjoxNjk1MzA1OTQ3LCJpYXQiOjE2OTUxMzMxNDd9.fW20Ri7BNsyfNVQ1AJAWMnlLHKQEhp6pi3wLCE3f4G8 --userType mojang --tweakClass net.minecraftforge.fml.common.launcher.FMLTweaker --versionType Forge
[09:05:04] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[09:05:04] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker

[09:05:04] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker

[09:05:04] [main/INFO] [FML]: Forge Mod Loader version 14.23.5.2847 for Minecraft 1.12.2 loading

[09:05:04] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_361, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_361

[09:05:05] [main/WARN] [FML]: The coremod FMLCorePlugin (net.minecraftforge.fml.relauncher.FMLCorePlugin) is not signed!

[09:05:05] [main/WARN] [FML]: The coremod FMLForgePlugin (net.minecraftforge.classloading.FMLForgePlugin) is not signed!

[09:05:05] [main/INFO] [FML]: Searching D:\特别整合包\TFC\.minecraft\mods for mods

[09:05:06] [main/WARN] [FML]: The coremod me.towdium.jecharacters.core.JechCore does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[09:05:06] [main/WARN] [FML]: The coremod JechCore (me.towdium.jecharacters.core.JechCore) is not signed!

[09:05:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in AppleCore-mc1.12.2-3.4.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

[09:05:06] [main/WARN] [FML]: The coremod AppleCore (squeek.applecore.AppleCore) is not signed!

[09:05:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in BetterWithLib-1.12-1.5.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

[09:05:06] [main/WARN] [FML]: The coremod LoadingPlugin (betterwithmods.library.core.LoadingPlugin) is not signed!

[09:05:06] [main/WARN] [FML]: The coremod darkness (io.github.yamporg.darkness.LoadingPlugin) is not signed!

[09:05:06] [main/WARN] [FML]: The coremod ivorius.ivtoolkit.IvToolkitLoadingPlugin does not have a MCVersion annotation, it may cause issues with this version of Minecraft

[09:05:06] [main/WARN] [FML]: The coremod IvToolkit (ivorius.ivtoolkit.IvToolkitLoadingPlugin) is not signed!

[09:05:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in Quark-r1.6-179.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

[09:05:06] [main/WARN] [FML]: The coremod Quark Plugin (vazkii.quark.base.asm.LoadingPlugin) is not signed!

[09:05:06] [main/WARN] [FML]: Found FMLCorePluginContainsFMLMod marker in UniversalTweaks-1.12.2-1.8.0.jar. This is not recommended, @Mods should be in a separate jar from the coremod.

[09:05:06] [main/ERROR] [LaunchWrapper]: Unable to launch

java.lang.RuntimeException: An error occurred trying to configure the Minecraft home at D:\特别整合包\TFC\.minecraft for Forge Mod Loader

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:111) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:81) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:42) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:141) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]

	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]

Caused by: java.lang.NoClassDefFoundError: zone/rong/mixinbooter/IEarlyMixinLoader

	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361]

	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]

	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_361]

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_361]

	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_361]

	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]

	... 5 more

Caused by: java.lang.ClassNotFoundException: zone.rong.mixinbooter.IEarlyMixinLoader

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361]

	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]

	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_361]

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_361]

	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_361]

	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]

	... 5 more

Caused by: java.lang.NullPointerException

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_361]

	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_361]

	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_361]

	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_361]

	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_361]

	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_361]

	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_361]

	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:527) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:451) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:265) ~[forge-1.12.2-14.23.5.2847.jar:?]

	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:107) ~[forge-1.12.2-14.23.5.2847.jar:?]

	... 5 more

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: net.minecraftforge.fml.relauncher.FMLSecurityManager$ExitTrappedException

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLSecurityManager.checkPermission(FMLSecurityManager.java:49)

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.SecurityManager.checkExit(Unknown Source)

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Runtime.exit(Unknown Source)

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.System.exit(Unknown Source)

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:138)

[09:05:06] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

Exception in thread "main"

**Comment by ACGaming** [comment]
Make sure to download install the dependencies [MixinBooter](https://www.curseforge.com/minecraft/mc-mods/mixin-booter) and [ConfigAnytime](https://www.curseforge.com/minecraft/mc-mods/configanytime) as well!
