### ISSUE TITLE
debug.log FML ERROR: `UniversalTweaks-1.12.2-1.10.0.jar - probably a corrupt zip`

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#406]
Loading game with UT output this errors in debug.log file. Its not causing crash and seems like mod features working normally.
I just worried there is something broken that i don't know.

```ruby
[Client thread/ERROR] [FML]: Unable to read a class file correctly
java.lang.IllegalArgumentException: null
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:185) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:168) ~[asm-debug-all-5.2.jar:5.2]
	at org.objectweb.asm.ClassReader.<init>(ClassReader.java:439) ~[asm-debug-all-5.2.jar:5.2]
  [...]
```
```ruby
[Client thread/ERROR] [FML]: There was a problem reading the entry META-INF/versions/9/module-info.class in the jar E:\mc\packs\E2E-E\minecraft\mods\UniversalTweaks-1.12.2-1.10.0.jar - probably a corrupt zip
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.redirect$xxx000$redirectNewASMModParser(JarDiscoverer.java:561) ~[JarDiscoverer.class:?]
  [...]
```
```ruby
[Client thread/WARN] [FML]: Zip file UniversalTweaks-1.12.2-1.10.0.jar failed to read properly, it will be ignored
net.minecraftforge.fml.common.LoaderException: java.lang.IllegalArgumentException

	at net.minecraftforge.fml.common.discovery.asm.ASMModParser.<init>(ASMModParser.java:63) ~[ASMModParser.class:?]
	at net.minecraftforge.fml.common.discovery.JarDiscoverer.redirect$xxx000$redirectNewASMModParser(JarDiscoverer.java:561) ~[JarDiscoverer.class:?]
  [...]
```

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/14663927/debug.log)

**Comment by ACGaming** [comment]
We have talked about this before, not critical and is going to be solved in the upcoming versions.

**Comment by Krutoy242** [comment]
Ok, seems like i forgot to add this error to filter, sorry.

**Comment by ACGaming** [comment]
No worries, just to reassure you it's still the same!
