### ISSUE TITLE
`sapling behavior` tweak not working

### ISSUE THREAD

**Issue by Krutoy242** [ACGaming/UniversalTweaks#408]
My config:

```cfg
"sapling behavior" {
    # Allows customization of sapling behavior while utilizing an optimized method
    B:"[1] Sapling Behavior Toggle"=true
    # Inclusive minimum light level at which saplings grow into trees
    I:"[2] Minimum Light Level"=9
    # Chance per update tick at which saplings grow into trees
    # Note: General growth rate is still affected by the random tick speed
    # Min: 0.0
    # Max: 1.0
    D:"[3] Growth Chance"=1.0
}
```

Despite `Growth Chance` set to 100%, i can see that saplings not grow:

![image](https://github.com/ACGaming/UniversalTweaks/assets/936618/b80c01bc-dced-4eff-84e6-26bfe5471db3)

I also found this WARN in `debug.log` file:

```ruby
[Client thread/WARN] [mixin]: Mixin apply for mod unknown-owner failed mixins.tweaks.blocks.sapling.json:UTSaplingMixin from mod unknown-owner -> net.minecraft.block.BlockSapling: org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException @Overwrite method TickCentral_TrueUpdateTick in mixins.tweaks.blocks.sapling.json:UTSaplingMixin from mod unknown-owner was not located in the target class net.minecraft.block.BlockSapling. Using refmap universaltweaks.refmap.json
org.spongepowered.asm.mixin.transformer.throwables.InvalidMixinException: @Overwrite method TickCentral_TrueUpdateTick in mixins.tweaks.blocks.sapling.json:UTSaplingMixin from mod unknown-owner was not located in the target class net.minecraft.block.BlockSapling. Using refmap universaltweaks.refmap.json
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachSpecialMethod(MixinPreProcessorStandard.java:436) ~[!mixinbooter-9.1-patched.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachOverwriteMethod(MixinPreProcessorStandard.java:416) ~[!mixinbooter-9.1-patched.jar:?]
	at org.spongepowered.asm.mixin.transformer.MixinPreProcessorStandard.attachMethods(MixinPreProcessorStandard.java:346) ~[!mixinbooter-9.1-patched.jar:?]
  [...]
```

[debug.log](https://github.com/ACGaming/UniversalTweaks/files/14665118/debug.log)

**Comment by Krutoy242** [comment]
Tiquality is not installed on my modpack.

**Comment by ACGaming** [comment]
Keep in mind that this doesn't change the actual speed of tree growth, it just affects another random chance until a tree can grow.

**Comment by Krutoy242** [comment]
Thank you for the fix!
