### ISSUE TITLE
Crash - Tesselating Block Model NullPointerException

### ISSUE THREAD

**Issue by Biliniko** [ACGaming/UniversalTweaks#526]
Hello,

While using the Universal Tweaks mod, my Minecraft client crashed when loading the world. Below are the detailed error log and related information:

Server core: Catserver
Universal Tweaks version: 1.11.0
Applied Energistics 2 (AE2) version: rv6-stable-7

**Error log:**
```
[11:15:14] [Client thread/ERROR] [Universal Tweaks]: UTBlockOverlay ::: Error rendering nearby blocks
net.minecraft.util.ReportedException: Tesselating block model
    at net.minecraft.client.renderer.BlockModelRenderer.func_187493_a(BlockModelRenderer.java:95) ~[bvo.class:?]
    at net.minecraft.client.renderer.BlockModelRenderer.func_178267_a(BlockModelRenderer.java:58) ~[bvo.class:?]
    at mod.acgaming.universaltweaks.bugfixes.blocks.blockoverlay.UTBlockOverlay.lambda$renderNearbyBlocks$2(UTBlockOverlay.java:69) ~[UTBlockOverlay.class:?]
    ...
Caused by: java.lang.NullPointerException
    at appeng.client.render.model.DriveBakedModel.func_188616_a(DriveBakedModel.java:73) ~[DriveBakedModel.class:?]
    ...
```

**Detailed description:**
The client suddenly crashed when switching servers and loading the world. The error log shows that the Universal Tweaks mod encountered a NullPointerException while rendering nearby blocks, specifically caused by the DriveBakedModel.func_188616_a method.

I hope this information helps in locating and resolving the issue. If you need any more information, please feel free to contact me.

Thank you for your help!

**Comment by ACGaming** [comment]
Either add `appliedenergistics2:drive` to the Block Overlay bugfix blacklist or disable the feature under `Bugfixes -> Blocks` entirely. I'll populate the blacklist with this entry for the next update.
